###
POST http://localhost:8080/init_game

###
GET http://localhost:8080/get_game?id=6e7a3251-2d46-4e15-8d54-0a3739b1be0e

###
POST http://localhost:8080/create_unit?card_id=80cbfcb0-1111-4e44-a484-a222d665f05b&game_id=6e7a3251-2d46-4e15-8d54-0a3739b1be0e&field_num=1

###
GET http://localhost:8080/get_unit?id=4bbdb621-1b6d-41ed-a9e4-53589da9cca4

###


###
POST http://localhost:8080/move_unit?unit_id=move_to_field

###
POST http://localhost:8080/create_card?name=&damage=&speed=&health=
Content-Type: application/json
