###
POST http://localhost:8080/init_game

###
GET http://localhost:8080/get_game?id=9b20410d-3fd8-4c54-b1ee-a7408903939a

###
POST http://localhost:8080/create_unit?card_id=80cbfcb0-1111-4e44-a484-a222d665f05b

###
GET http://localhost:8080/get_unit?id=

###
POST http://localhost:8080/move_unit
Content-Type: application/json

{
  "game_id": "",
  "unit_id": "",
  "move_to_field": ""
}
